### ISSUE TITLE
Question about NoesisBlueprintGeneratedClass

### ISSUE THREAD

**Issue by jashking** [Noesis/UE4Plugin#13]
Hi, I am curious about the using of UNoesisBlueprintGeneratedClass, why not just make BaseXaml/EnablePPAA/TessellationQuality editable in UNoesisInstance and assign them in the blueprint?

**Comment by hcpizzi** [comment]
EnablePPAA and TessellationQuality are BlueprintReadWrite in NoesisInstance, and they are applied at the beginning of each update. The values that come from the NoesisBlueprint are the initial values.

Regarding the BaseXaml, the idea was that the class resulting from compiling the NoesisBlueprint (NoesisView in the editor), that is, the NoesisInstance subclass itself, would be the DataContext for said loaded XAML. That is still the case, and that's why we thought it made sense to specify the NoesisXaml in the blueprint, since they'd be made for one another. Having said that, we later introduced the ability to set the DataContext externally, and there's really nothing that prevents changing the XAML at runtime that I can think of right now.
