### ISSUE TITLE
Error C2259 when packaging Neosis with binary ue4 4.23

### ISSUE THREAD

**Issue by Pantong51** [Noesis/UE4Plugin#20]
ERROR: https://pastebin.com/d42TPGAX
BUILD.CS https://pastebin.com/fAwmCM38

This is the error, I've added neosis to an almost blank ue4 project and attempted to package. Not really sure what I should do here or how to fix it.

**Comment by hcpizzi** [comment]
Hi Pantong51,

I think this is caused by unity builds and should be fixed for our next release targeting UE4.24 and Noesis SDK 2.2.6.

For now, could you try disabling unity builds for our MorphemeRuntime module. In order to do so in UE4.23, edit Plugins/NoesisGUI/Source/NoesisRuntime/NoesisRuntime.Build.cs, and add the following line around line 15:

`bFasterWithoutUnity = true;`

Please, let us know if this workaround works for you.

**Comment by Pantong51** [comment]
Oh, snap. I'll give it a shot sometime this weekend and let you know. Thanks for the quick response.

**Comment by hcpizzi** [comment]
No worries. Let us know if that works for you until we fix it for good.

**Comment by Pantong51** [comment]
Seamed to work for me. Thank you.
